INSERT INTO one_minute
SELECT * FROM AUDCAD;

INSERT INTO one_minute
SELECT * FROM AUDJPY;

INSERT INTO one_minute
SELECT * FROM AUDNZD;

INSERT INTO one_minute
SELECT * FROM AUDUSD;

INSERT INTO one_minute
SELECT * FROM CADJPY;

INSERT INTO one_minute
SELECT * FROM EURAUD;

INSERT INTO one_minute
SELECT * FROM EURCAD;

INSERT INTO one_minute
SELECT * FROM EURGBP;

INSERT INTO one_minute
SELECT * FROM EURJPY;

INSERT INTO one_minute
SELECT * FROM EURNZD;

INSERT INTO one_minute
SELECT * FROM EURUSD;

INSERT INTO one_minute
SELECT * FROM GBPAUD;

INSERT INTO one_minute
SELECT * FROM GBPCAD;

INSERT INTO one_minute
SELECT * FROM GBPJPY;

INSERT INTO one_minute
SELECT * FROM GBPNZD;

INSERT INTO one_minute
SELECT * FROM GBPUSD;

INSERT INTO one_minute
SELECT * FROM NZDCAD;

INSERT INTO one_minute
SELECT * FROM NZDJPY;

INSERT INTO one_minute
SELECT * FROM NZDUSD;

INSERT INTO one_minute
SELECT * FROM USDCAD;

INSERT INTO one_minute
SELECT * FROM USDJPY;